import React, { useState, useMemo, useEffect } from "react";
import { motion } from "framer-motion";
import {
  Eye, Calendar, Sparkles, KeyRound, CheckCircle2, Search,
  ChevronLeft, ChevronRight, Copy, Store as StoreIcon,
} from "lucide-react";
import toast from "react-hot-toast";
import { useTable, useCurrentMember } from "../lib/useData";
import { supabase } from "../lib/supabase";
import { formatDate, generateReferralCode } from "../lib/helpers";
import { Badge } from "./ui";

const DAY_NAMES = ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"];

function getWeekStart(date) {
  const d = new Date(date);
  const day = d.getDay();
  const diff = day === 0 ? -6 : 1 - day;
  d.setDate(d.getDate() + diff);
  d.setHours(0, 0, 0, 0);
  return d;
}

function formatWeekRange(start) {
  const end = new Date(start);
  end.setDate(end.getDate() + 6);
  const startStr = formatDate(start, "MMM d");
  const endStr = formatDate(end, "MMM d");
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const isThisWeek = start.getTime() === getWeekStart(today).getTime();
  return `${startStr} – ${endStr}${isThisWeek ? " (this week)" : ""}`;
}

function getTimeUntilWeekEnd() {
  const now = new Date();
  const end = getWeekStart(now);
  end.setDate(end.getDate() + 7);
  let diff = Math.floor((end - now) / 1000);
  const days = Math.floor(diff / 86400);
  diff -= days * 86400;
  const h = Math.floor(diff / 3600);
  diff -= h * 3600;
  const m = Math.floor(diff / 60);
  const s = diff - m * 60;
  return `${days}d ${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
}

export default function StorePanel() {
  const [weekOffset, setWeekOffset] = useState(0);
  const [weekCountdown, setWeekCountdown] = useState(getTimeUntilWeekEnd());
  const [selectedUsername, setSelectedUsername] = useState("");
  const [usernameSearch, setUsernameSearch] = useState("");
  const [genCount, setGenCount] = useState("1");
  const [genUsername, setGenUsername] = useState("");
  const [genBusy, setGenBusy] = useState(false);
  const [availSearch, setAvailSearch] = useState("");
  const [myCodesSearch, setMyCodesSearch] = useState("");
  const [weeklyFilterUser, setWeeklyFilterUser] = useState("");

  const { data: members = [] } = useTable("members");
  const { data: allCodes = [], refetch: refetchCodes } = useTable("maintenance_codes");
  const { currentMember } = useCurrentMember(members);

  useEffect(() => {
    const interval = setInterval(() => setWeekCountdown(getTimeUntilWeekEnd()), 1000);
    return () => clearInterval(interval);
  }, []);

  // Codes allotted by admin to this store (assigned_sub_admin_id === store.id)
  const allottedCodes = useMemo(
    () => allCodes.filter(c => c.assigned_sub_admin_id === currentMember?.id),
    [allCodes, currentMember]
  );

  // Codes generated by this store
  const myGeneratedCodes = useMemo(
    () => allCodes.filter(c => c.generated_by_member_id === currentMember?.id).sort((a, b) => new Date(b.created_at) - new Date(a.created_at)),
    [allCodes, currentMember]
  );

  const allottedCount = allottedCodes.length;
  const generatedCount = myGeneratedCodes.length;
  const remainingCount = Math.max(0, allottedCount - generatedCount);

  // Codes Added by Admin — grouped by date
  const codesAddedByAdmin = useMemo(() => {
    const byDate = {};
    allottedCodes.forEach(c => {
      const dateKey = formatDate(c.created_at, "MMM d, yyyy h:mm a");
      if (!byDate[dateKey]) byDate[dateKey] = { date: dateKey, count: 0 };
      byDate[dateKey].count++;
    });
    return Object.values(byDate).sort((a, b) => new Date(b.date) - new Date(a.date));
  }, [allottedCodes]);

  // Available codes — codes generated by this store that are designated to members and not yet used
  const availableCodes = useMemo(() => {
    let codes = myGeneratedCodes.filter(c => !c.is_used && c.assigned_username);
    if (availSearch) {
      const q = availSearch.toLowerCase();
      codes = codes.filter(c => (c.assigned_username || "").toLowerCase().includes(q));
    }
    return codes;
  }, [myGeneratedCodes, availSearch]);

  // Filtered generated codes for "My Generated Codes" table
  const filteredMyCodes = useMemo(() => {
    let codes = myGeneratedCodes;
    if (myCodesSearch) {
      const q = myCodesSearch.toLowerCase();
      codes = codes.filter(c => (c.assigned_username || "").toLowerCase().includes(q) || (c.code || "").toLowerCase().includes(q));
    }
    return codes;
  }, [myGeneratedCodes, myCodesSearch]);

  // Weekly redeemed codes
  const weekStart = useMemo(() => {
    const base = getWeekStart(new Date());
    base.setDate(base.getDate() + weekOffset * 7);
    return base;
  }, [weekOffset]);

  const weekEnd = useMemo(() => {
    const e = new Date(weekStart);
    e.setDate(e.getDate() + 6);
    e.setHours(23, 59, 59, 999);
    return e;
  }, [weekStart]);

  // All redeemed codes by members designated by this store's generated codes
  const weeklyRedeemed = useMemo(() => {
    const myCodeIds = new Set(myGeneratedCodes.map(c => c.id));
    return allCodes.filter(c => c.is_used && myCodeIds.has(c.id) && c.used_at && new Date(c.used_at) >= weekStart && new Date(c.used_at) <= weekEnd);
  }, [allCodes, myGeneratedCodes, weekStart, weekEnd]);

  // Build weekly table rows — one row per designated username (or filter by selected)
  const weeklyRows = useMemo(() => {
    const userMap = {};
    weeklyRedeemed.forEach(c => {
      const u = c.assigned_username || "—";
      if (!userMap[u]) userMap[u] = { username: u, counts: [0, 0, 0, 0, 0, 0, 0] };
      const d = new Date(c.used_at);
      const dayIdx = (d.getDay() + 6) % 7;
      userMap[u].counts[dayIdx]++;
    });
    let rows = Object.values(userMap).sort((a, b) => a.username.localeCompare(b.username));
    if (weeklyFilterUser) {
      rows = rows.filter(r => r.username.toLowerCase().includes(weeklyFilterUser.toLowerCase()));
    }
    return rows;
  }, [weeklyRedeemed, weeklyFilterUser]);

  // Approved members for the "Designate to username" dropdown
  const approvedMembers = useMemo(() => members.filter(m => m.status === "approved"), [members]);

  async function handleGenerate() {
    const count = parseInt(genCount) || 1;
    if (count < 1) { toast.error("Enter a valid count"); return; }
    if (count > remainingCount) { toast.error(`Only ${remainingCount} codes remaining in your allotment`); return; }
    setGenBusy(true);
    try {
      const records = [];
      for (let i = 0; i < count; i++) {
        const base = "MAINT-" + generateReferralCode();
        const code = genUsername ? `${base}-@${genUsername.toUpperCase()}` : base;
        records.push({
          code,
          is_used: false,
          assigned_username: genUsername || null,
          generated_by_member_id: currentMember.id,
        });
      }
      await supabase.from("maintenance_codes").insert(records);
      toast.success(`${count} code(s) generated!`);
      setGenCount("1");
      setGenUsername("");
      refetchCodes();
    } catch (err) {
      toast.error("Failed to generate codes");
    }
    setGenBusy(false);
  }

  async function copyCode(code) {
    try { await navigator.clipboard.writeText(code); toast.success("Code copied!"); }
    catch { toast.error("Failed to copy"); }
  }

  if (!currentMember) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-gray-200 border-t-gray-800 rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 py-8">
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} className="mb-8 flex items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 bg-gradient-to-br from-orange-500 to-amber-600 rounded-2xl flex items-center justify-center shadow-lg">
            <Eye className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Store Panel Monitor</h1>
            <p className="text-gray-500 text-sm">Manage codes allotted to your store</p>
          </div>
        </div>
        {/* Username selector */}
        <div className="relative">
          <select
            value={selectedUsername}
            onChange={e => setSelectedUsername(e.target.value)}
            className="h-11 rounded-xl border border-gray-200 px-4 pr-10 outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-500/20 bg-white text-sm font-medium text-gray-700 min-w-[200px]"
          >
            <option value="">All users</option>
            {approvedMembers.map(m => (
              <option key={m.id} value={m.username}>@{m.username} — {m.full_name}</option>
            ))}
          </select>
        </div>
      </motion.div>

      {/* Top status cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
          className="bg-white rounded-2xl shadow-lg border border-gray-100 p-5 flex items-center gap-4">
          <div className="w-12 h-12 bg-orange-100 rounded-xl flex items-center justify-center shrink-0">
            <StoreIcon className="w-6 h-6 text-orange-500" />
          </div>
          <div>
            <p className="text-3xl font-extrabold text-gray-900">{allottedCount}</p>
            <p className="text-sm text-gray-500 font-medium">Allotted by Admin</p>
          </div>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}
          className="bg-white rounded-2xl shadow-lg border border-gray-100 p-5 flex items-center gap-4">
          <div className="w-12 h-12 bg-blue-100 rounded-xl flex items-center justify-center shrink-0">
            <Sparkles className="w-6 h-6 text-blue-500" />
          </div>
          <div>
            <p className="text-3xl font-extrabold text-gray-900">{generatedCount}</p>
            <p className="text-sm text-gray-500 font-medium">Generated</p>
          </div>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
          className="bg-white rounded-2xl shadow-lg border border-gray-100 p-5 flex items-center gap-4">
          <div className="w-12 h-12 bg-green-100 rounded-xl flex items-center justify-center shrink-0">
            <CheckCircle2 className="w-6 h-6 text-green-500" />
          </div>
          <div>
            <p className="text-3xl font-extrabold text-gray-900">{remainingCount}</p>
            <p className="text-sm text-gray-500 font-medium">Remaining</p>
          </div>
        </motion.div>
      </div>

      {/* Codes Added by Admin */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}
        className="bg-white rounded-2xl shadow-lg border border-gray-100 mb-6 overflow-hidden">
        <div className="p-5 border-b border-gray-100 flex items-center gap-3">
          <div className="w-10 h-10 bg-orange-50 rounded-xl flex items-center justify-center">
            <Calendar className="w-5 h-5 text-orange-500" />
          </div>
          <h2 className="text-lg font-bold text-gray-900">Codes Added by Admin</h2>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200">
                <th className="text-left py-2.5 px-5 font-semibold text-gray-500 uppercase text-xs">Date</th>
                <th className="text-left py-2.5 px-5 font-semibold text-gray-500 uppercase text-xs">Codes Added</th>
              </tr>
            </thead>
            <tbody>
              {codesAddedByAdmin.length === 0 ? (
                <tr><td colSpan="2" className="text-center py-8 text-gray-400">No codes allotted yet</td></tr>
              ) : codesAddedByAdmin.map((row, i) => (
                <tr key={i} className="border-b border-gray-50">
                  <td className="py-3 px-5 text-gray-700">{row.date}</td>
                  <td className="py-3 px-5 font-bold text-green-600">+{row.count}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </motion.div>

      {/* Generate Codes */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
        className="bg-white rounded-2xl shadow-lg border border-gray-100 mb-6 overflow-hidden">
        <div className="p-5 border-b border-gray-100 flex items-center gap-3">
          <div className="w-10 h-10 bg-green-50 rounded-xl flex items-center justify-center">
            <Sparkles className="w-5 h-5 text-green-500" />
          </div>
          <h2 className="text-lg font-bold text-gray-900">Generate Codes</h2>
        </div>
        <div className="p-5">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 items-end">
            <div>
              <label className="text-sm font-medium text-gray-600 mb-1.5 block">Number of codes</label>
              <input type="number" value={genCount} onChange={e => setGenCount(e.target.value)} min="1"
                className="w-full h-11 rounded-xl border border-gray-200 px-4 outline-none focus:border-green-500 focus:ring-2 focus:ring-green-500/20" />
            </div>
            <div>
              <label className="text-sm font-medium text-gray-600 mb-1.5 block">Designate to username</label>
              <select value={genUsername} onChange={e => setGenUsername(e.target.value)}
                className="w-full h-11 rounded-xl border border-gray-200 px-4 outline-none focus:border-green-500 focus:ring-2 focus:ring-green-500/20 bg-white">
                <option value="">No one (unassigned)</option>
                {approvedMembers.map(m => (
                  <option key={m.id} value={m.username}>@{m.username}</option>
                ))}
              </select>
            </div>
            <button onClick={handleGenerate} disabled={genBusy || remainingCount <= 0}
              className="h-11 px-6 rounded-xl bg-green-600 hover:bg-green-700 text-white font-bold transition-colors disabled:opacity-40 disabled:pointer-events-none">
              {genBusy ? "Generating..." : "Generate"}
            </button>
          </div>
          {remainingCount <= 0 && (
            <p className="text-sm text-red-500 mt-3">No codes remaining in your allotment. Ask admin to allot more codes.</p>
          )}
        </div>
      </motion.div>

      {/* Weekly Redeemed Codes */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.25 }}
        className="bg-white rounded-2xl shadow-lg border border-gray-100 mb-6 overflow-hidden">
        <div className="p-5 border-b border-gray-100">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 bg-indigo-50 rounded-xl flex items-center justify-center">
              <Calendar className="w-5 h-5 text-indigo-500" />
            </div>
            <h2 className="text-lg font-bold text-gray-900">Weekly Redeemed Codes (Mon – Sun)</h2>
            <div className="ml-auto flex items-center gap-2">
              <button onClick={() => setWeekOffset(w => w - 1)}
                className="w-8 h-8 rounded-lg border border-gray-200 flex items-center justify-center text-gray-500 hover:bg-gray-50 transition-colors">
                <ChevronLeft className="w-4 h-4" />
              </button>
              <span className="text-sm font-medium text-gray-700 min-w-[180px] text-center">{formatWeekRange(weekStart)}</span>
              <button onClick={() => setWeekOffset(w => w + 1)} disabled={weekOffset >= 0}
                className="w-8 h-8 rounded-lg border border-gray-200 flex items-center justify-center text-gray-500 hover:bg-gray-50 transition-colors disabled:opacity-30 disabled:pointer-events-none">
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>
          <div className="flex items-center justify-between gap-4">
            <p className="text-gray-500 text-sm">Minimum 5 redeemed codes every calendar week (Monday – Sunday).</p>
            <select value={weeklyFilterUser} onChange={e => setWeeklyFilterUser(e.target.value)}
              className="h-9 rounded-lg border border-gray-200 px-3 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 bg-white text-sm text-gray-700">
              <option value="">Filter by username</option>
              {approvedMembers.map(m => (
                <option key={m.id} value={m.username}>@{m.username}</option>
              ))}
            </select>
          </div>
        </div>
        <div className="p-5">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-200">
                  <th className="text-left py-2 px-3 font-semibold text-gray-500 uppercase text-xs">User</th>
                  {DAY_NAMES.map((day, i) => {
                    const date = new Date(weekStart);
                    date.setDate(date.getDate() + i);
                    return (
                      <th key={day} className="text-center py-2 px-2 font-semibold text-gray-500 uppercase text-xs whitespace-nowrap">
                        {day} <span className="text-gray-400">{formatDate(date, "d")}</span>
                      </th>
                    );
                  })}
                  <th className="text-center py-2 px-3 font-semibold text-gray-500 uppercase text-xs">Total</th>
                  <th className="text-center py-2 px-3 font-semibold text-gray-500 uppercase text-xs">Status</th>
                </tr>
              </thead>
              <tbody>
                {weeklyRows.length === 0 ? (
                  <tr><td colSpan="10" className="text-center py-6 text-gray-400">No redeemed codes this week</td></tr>
                ) : weeklyRows.map((row, i) => {
                  const total = row.counts.reduce((a, b) => a + b, 0);
                  const needed = Math.max(0, 5 - total);
                  return (
                    <tr key={i} className="border-b border-gray-50">
                      <td className="py-3 px-3 font-medium text-gray-900">@{row.username}</td>
                      {row.counts.map((count, j) => (
                        <td key={j} className="text-center py-3 px-2 text-gray-400">
                          {count > 0 ? <span className="font-semibold text-gray-900">{count}</span> : "—"}
                        </td>
                      ))}
                      <td className="text-center py-3 px-3 font-bold text-gray-900">{total}/5</td>
                      <td className="text-center py-3 px-3">
                        {needed > 0 ? (
                          <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium bg-yellow-100 text-yellow-700">
                            {needed} more needed
                          </span>
                        ) : (
                          <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium bg-green-100 text-green-700">
                            Complete
                          </span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
          <p className="text-purple-600 text-sm font-medium mt-4">Week ends in {weekCountdown}</p>
        </div>
      </motion.div>

      {/* Available Codes */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}
        className="bg-white rounded-2xl shadow-lg border border-gray-100 mb-6 overflow-hidden">
        <div className="p-5 border-b border-gray-100">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 bg-teal-50 rounded-xl flex items-center justify-center">
              <KeyRound className="w-5 h-5 text-teal-500" />
            </div>
            <h2 className="text-lg font-bold text-gray-900">Available Codes</h2>
          </div>
          <p className="text-gray-500 text-sm">Codes designated to members. Redeem on their behalf when the timer unlocks.</p>
        </div>
        <div className="p-5">
          <div className="relative mb-4">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              value={availSearch}
              onChange={e => setAvailSearch(e.target.value)}
              placeholder="Search by username..."
              className="w-full h-11 rounded-xl border border-gray-200 pl-10 pr-4 outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-500/20"
            />
          </div>
          {availableCodes.length === 0 ? (
            <div className="text-center py-10">
              <p className="text-gray-400 text-sm">No available codes. Generate codes with a designated username to see them here.</p>
            </div>
          ) : (
            <div className="space-y-2">
              {availableCodes.map(c => (
                <div key={c.id} className="flex items-center justify-between bg-teal-50 rounded-xl px-4 py-3">
                  <code className="font-mono text-sm font-bold text-gray-900">{c.code}</code>
                  <span className="text-sm text-gray-500">@{c.assigned_username}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </motion.div>

      {/* My Generated Codes */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.35 }}
        className="bg-white rounded-2xl shadow-lg border border-gray-100 overflow-hidden">
        <div className="p-5 border-b border-gray-100 flex items-center gap-3">
          <div className="w-10 h-10 bg-purple-50 rounded-xl flex items-center justify-center">
            <KeyRound className="w-5 h-5 text-purple-500" />
          </div>
          <h2 className="text-lg font-bold text-gray-900">My Generated Codes</h2>
        </div>
        <div className="p-5">
          <div className="relative mb-4">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              value={myCodesSearch}
              onChange={e => setMyCodesSearch(e.target.value)}
              placeholder="Search by username..."
              className="w-full h-11 rounded-xl border border-gray-200 pl-10 pr-4 outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20"
            />
          </div>
          {filteredMyCodes.length === 0 ? (
            <div className="text-center py-10">
              <p className="text-gray-400 text-sm">No codes generated yet. Use the Generate Codes section above to create codes.</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-gray-200">
                    <th className="text-left py-2.5 px-3 font-semibold text-gray-500 uppercase text-xs">Code</th>
                    <th className="text-left py-2.5 px-3 font-semibold text-gray-500 uppercase text-xs">Designated To</th>
                    <th className="text-left py-2.5 px-3 font-semibold text-gray-500 uppercase text-xs">Status</th>
                    <th className="text-left py-2.5 px-3 font-semibold text-gray-500 uppercase text-xs">Generated</th>
                    <th className="text-left py-2.5 px-3 font-semibold text-gray-500 uppercase text-xs">Used Date</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredMyCodes.map(c => (
                    <tr key={c.id} className="border-b border-gray-50 hover:bg-gray-50">
                      <td className="py-3 px-3">
                        <div className="flex items-center gap-2">
                          <code className="font-mono text-sm font-bold text-gray-900">{c.code}</code>
                          <button onClick={() => copyCode(c.code)} className="text-gray-400 hover:text-gray-600">
                            <Copy className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </td>
                      <td className="py-3 px-3 text-gray-600">{c.assigned_username ? `@${c.assigned_username}` : "—"}</td>
                      <td className="py-3 px-3">
                        <Badge className={c.is_used ? "bg-gray-100 text-gray-500" : "bg-green-100 text-green-700"}>
                          {c.is_used ? "Used" : "Available"}
                        </Badge>
                      </td>
                      <td className="py-3 px-3 text-gray-500">{formatDate(c.created_at, "MMM d, yyyy h:mm a")}</td>
                      <td className="py-3 px-3 text-gray-500">{c.used_at ? formatDate(c.used_at, "MMM d, yyyy h:mm a") : "—"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </motion.div>
    </div>
  );
}
